[package]
name = "macroquad_term"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
log = "0.4.22"
macroquad = {version = "0.4.13", features=["log"]}
opener = "0.7.2"
serde = {version = "1.0.214", features=["derive"]}
serde_json = "1.0.132"
simple_logger = "5.0.0"

